












# Funding options for Graphic Novel Video Creator

github: your-github-username
patreon: your-patreon-username
ko_fi: your-ko-fi-username
tidelift: tidelift-package/npm/graphic-novel-video-creator
community_bridge: graphic-novel-video-creator
liberapay: your-liberapay-username
issuehunt: your-issuehunt-username










