























name: "Auto Close Invalid PRs"

on:
  pull_request_target:

jobs:
  validate-pr:
    runs-on: ubuntu-latest
    steps:
      - name: Validate PR title format
        uses: amannn/action-semantic-pull-request@v5
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Check for merge conflicts
        run: |
          if [ -n "$(git ls-files -u 2>/dev/null)" ]; then echo "Merge conflicts detected"; exit 1; fi

      - name: Close invalid PRs
        if: ${{ failure() }}
        uses: actions/github-script@v6
        with:
          script: |
            github.rest.issues.update({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              state: 'closed',
              body: 'This pull request has been automatically closed because it does not meet our contribution guidelines.'
            });























