























name: "Auto Approve Dependencies"

on:
  pull_request_target:

jobs:
  auto-approve:
    if: ${{ github.actor == 'dependabot[bot]' }}
    runs-on: ubuntu-latest
    steps:
      - name: Auto approve Dependabot PRs
        run: gh pr review --approve "${{ github.event.pull_request.html_url }}"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}























