






















name: "PR Title Validation"

on:
  pull_request_target:

jobs:
  validate-title:
    runs-on: ubuntu-latest
    steps:
      - name: Validate PR title format
        uses: amannn/action-semantic-pull-request@v5
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}






















