


















name: "Security Audit"

on:
  schedule:
    - cron: '0 0 * * 1' # Every Monday at midnight
  push:
    branches: [ main ]
    paths:
      - '**/requirements*.txt'
      - '**/setup.py'
      - '**/pyproject.toml'

jobs:
  security-audit:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v5

      - name: Set up Python 3.8
        uses: actions/setup-python@v5
        with:
          python-version: "3.8"

      - name: Install safety
        run: |
          pip install safety

      - name: Run security audit
        run: |
          safety check --file requirements.txt --full-report
















